version: "3.9"

services:
  wallet-db:
    image: mysql:8
    container_name: wallet-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: walletdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./walletdb:/var/lib/mysql
    restart: always
    networks:
      - wallet-network

networks:
  wallet-network:
    driver: bridge