server:
  port: 8080

  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

spring:
  application:
    name: ms-wallet-core

  # Jackson
  jackson:
    property-naming-strategy: SNAKE_CASE
    time-zone: UTC
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
    serialization:
      write-dates-as-timestamps: false

---
########################
## 'dev' profile only ##
########################
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    name: wallet
    jdbc-url: jdbc:mysql://${DATABASE_MYSQL_HOST:localhost}:${DATABASE_MYSQL_PORT:3306}/${DATABASE_MYSQL_DBNAME:walletdb}?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${DATABASE_MYSQL_USERNAME:user}
    password: ${DATABASE_MYSQL_PASSWORD:password}
    pool-size: 30

  flyway:
    locations: classpath:db/migration,classpath:db/populateData

  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_HOST:localhost:9092}
          auto-create-topics: true
      bindings:
        balanceUpdatedSupplier-out-0:
          destination: wallet-core.v1.event.balance-updated
          contentType: application/json
        transactionCreatedSupplier-out-0:
          destination: wallet-core.v1.event.transaction-created
          contentType: application/json