spring:
  #Database
  datasource:
    name: wallet
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://${wallet-core-db:localhost}/walletdb?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: user
    password: password
    pool-size: 30

  cloud:
    stream:
      binder:
        brokers: localhost:9092

server:
  port: 8080
