spring:
  #Database
  datasource:
    name: wallet
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://${wallet-core-db:localhost}/walletdb?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: user
    password: password
    pool-size: 30

  cloud:
    stream:
      bindings:
        balanceUpdatedSupplier-out-0:
          destination: wallet-core.v1.event.balance-updated
          contentType: application/json
        transactionCreatedSupplier-out-0:
          destination: wallet-core.v1.event.transaction-created
          contentType: application/json

server:
  port: 8080
