spring:
  #Database
  datasource:
    name: wallet-test
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:walletdbtest;DB_CLOSE_DELAY=-1
    username: sa
    password:
    maximum-pool-size: 1
  h2:
    console:
      enabled: true
