spring:
  #Database
  datasource:
    name: wallet
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://${wallet-db:localhost}/walletdb?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: user
    password: password
    pool-size: 30

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8080
