server:
  port: 8081

spring:
  application:
    name: ms-balance

  # Database - MongoDB
  data:
    mongodb:
      uri: mongodb://${DATABASE_MONGO_USERNAME:mongoadmin}:${DATABASE_MONGO_PASSWORD:secret}@${DATABASE_MONGO_HOST:127.0.0.1}:${DATABASE_MONGO_PORT:27017}/${DATABASE_MONGO_DBNAME:balancedb}?authSource=admin

  # Jackson
  jackson:
    property-naming-strategy: SNAKE_CASE
    time-zone: UTC
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
    serialization:
      write-dates-as-timestamps: false

  cloud:
    function:
      definition: balanceUpdatedEventListener;accountCreatedEventListener

    stream:
      kafka:
        binder:
          brokers: ${KAFKA_HOST:localhost:9092}

      bindings:
        balanceUpdatedEventListener-in-0:
          destination: wallet-core.v1.event.balance-updated
        accountCreatedEventListener-in-0:
          destination: wallet-core.v1.event.account-created