server:
  port: 8081

spring:
  application:
    name: ms-balance

  # Database - MongoDB
  data:
    mongodb:
      uri: mongodb://mongoadmin:secret@127.0.0.1:27017/balancedb?authSource=admin

  # Serialization - Jackson
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true

  cloud:
    stream:
      function:
        definition: BalanceUpdatedEventListener
      bindings:
        balanceUpdatedEventListener-in-0:
          destination: wallet-core.v1.event.balance-updated


# Metrics - Spring Actuator
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "metrics,health,info"
  metrics:
    enable:
      executor: false
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
    info:
      enabled: true