server:
  port: 8081

spring:
  application:
    name: ms-balance

  # Database - MongoDB
  data:
    mongodb:
      uri: mongodb://mongoadmin:secret@127.0.0.1:27017/balancedb?authSource=admin

  # Jackson
  jackson:
    property-naming-strategy: SNAKE_CASE
    time-zone: UTC
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
    serialization:
      write-dates-as-timestamps: false

  cloud:
    stream:
      function:
        definition: BalanceUpdatedEventListener
      bindings:
        balanceUpdatedEventListener-in-0:
          destination: wallet-core.v1.event.balance-updated